# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0002_auto_20170804_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='password',
            field=models.CharField(default='mayank', max_length=100),
        ),
        migrations.AlterField(
            model_name='firm',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
