# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_auto_20170908_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='voucher_type',
            field=models.CharField(choices=[('Imprest', 'Imprest'), ('Receive', 'Receive'), ('Expense', 'Expense'), ('Journal', 'Expense')], default='Journal', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucher',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Voucher'),
        ),
    ]
