# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0019_auto_20170909_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='voucher',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Voucher'),
        ),
    ]
