# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0001_initial'),
        ('home', '0002_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='firm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firm.Firm'),
            preserve_default=False,
        ),
    ]
