# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170803_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firm.Firm'),
        ),
    ]
