# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170803_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='firm',
        ),
    ]
