# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-12 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170805_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='temp1',
            new_name='balance_minus',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='temp2',
            new_name='balance_plus',
        ),
    ]
