# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170908_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ledger',
            name='dominant',
            field=models.CharField(default='Credit', max_length=7),
        ),
    ]
